local M = {}

local palette = {
	primary = "#FFA366",
	light = "#F0C3AA",
	lightest = "#FFF5E6",
	mono = "#161616",
	black = "#000000",
	blue1 = "#F5F5F5",
	blue2 = "#A7A9A5",
	blue3 = "#7A96A8",
	blue4 = "#4A90CC",
	blue5 = "#1B2B56",
	blue6 = "#0D1323",
	green1 = "#E5FEEB",
	green2 = "#CCEFD2",
	green3 = "#99C4BE",
	green4 = "#204F4F",
	green5 = "#2D4448",
	green6 = "#0E1C1E",
	red1 = "#E0D4D8",
	red2 = "#EECCBB",
	red3 = "#6B424F",
	red4 = "#552D39",
	red5 = "#371437",
	red6 = "#260608",
	yellow1 = "#DCD7C6",
	yellow2 = "#FFDDA8",
	yellow3 = "#FFBB77",
	yellow4 = "#B78452",
	yellow5 = "#605A4E",
	yellow6 = "#272112",
	-- Generated colors
	vibrant_red = "#FF7A66",
	magenta = "#D9A8C4",
	cyan = "#77B3B3",
	bright_blue = "#8FBFEE",
	bright_cyan = "#AADDDD",
}

local function hl(group, opts)
	vim.api.nvim_set_hl(0, group, opts)
end

function M.setup()
	-- Editor
	hl("Normal", { fg = palette.lightest, bg = palette.mono })
	hl("NormalNC", { fg = palette.lightest, bg = palette.mono })
	hl("NormalFloat", { fg = palette.lightest, bg = palette.black })
	hl("NormalSB", { fg = palette.lightest, bg = palette.black })
	hl("FloatBorder", { fg = palette.blue5, bg = palette.black })
	hl("FloatTitle", { fg = palette.primary, bg = palette.black, bold = true })
	hl("EndOfBuffer", { fg = palette.blue5 })
	hl("NonText", { fg = palette.yellow5 })
	hl("Whitespace", { fg = palette.blue5 })
	hl("Conceal", { fg = palette.blue4 })
	hl("LineNr", { fg = palette.blue3 })
	hl("LineNrAbove", { fg = palette.blue3 })
	hl("LineNrBelow", { fg = palette.blue3 })
	hl("CursorLine", { bg = palette.yellow6 })
	hl("CursorLineNr", { fg = palette.primary, bold = true })
	hl("CursorColumn", { bg = palette.yellow6 })
	hl("Cursor", { fg = palette.black, bg = palette.primary })
	hl("lCursor", { link = "Cursor" })
	hl("CursorIM", { link = "Cursor" })
	hl("MatchParen", { fg = palette.yellow1, bg = palette.yellow5, bold = true })
	hl("Visual", { bg = palette.yellow6 })
	hl("VisualNOS", { bg = palette.yellow6 })
	hl("Search", { fg = palette.black, bg = palette.yellow3 })
	hl("IncSearch", { fg = palette.black, bg = palette.primary })
	hl("CurSearch", { link = "IncSearch" })
	hl("Substitute", { fg = palette.black, bg = palette.vibrant_red })
	hl("Question", { fg = palette.blue4 })
	hl("SpecialKey", { fg = palette.blue5 })
	hl("Directory", { fg = palette.blue4 })
	hl("Title", { fg = palette.primary, bold = true })
	hl("ErrorMsg", { fg = palette.vibrant_red })
	hl("WarningMsg", { fg = palette.yellow3 })
	hl("MoreMsg", { fg = palette.blue4 })
	hl("ModeMsg", { fg = palette.blue2, bold = true })
	hl("MsgArea", { fg = palette.lightest })
	hl("QuickFixLine", { bg = palette.yellow6 })
	hl("StatusLine", { fg = palette.lightest, bg = palette.black })
	hl("StatusLineNC", { fg = palette.blue3, bg = palette.black })
	hl("WinBar", { fg = palette.lightest })
	hl("WinBarNC", { fg = palette.blue3 })
	hl("TabLine", { fg = palette.blue3, bg = palette.black })
	hl("TabLineFill", { bg = palette.black })
	hl("TabLineSel", { fg = palette.primary, bg = palette.mono, bold = true })
	hl("VertSplit", { fg = palette.blue5 })
	hl("WinSeparator", { fg = palette.blue5 })
	hl("SignColumn", { bg = palette.mono })
	hl("SignColumnSB", { fg = palette.blue3, bg = palette.black })
	hl("FoldColumn", { fg = palette.blue4, bg = palette.mono })
	hl("Folded", { fg = palette.blue3, bg = palette.yellow6 })
	hl("ColorColumn", { bg = palette.yellow5 })
	hl("Pmenu", { fg = palette.lightest, bg = palette.yellow6 })
	hl("PmenuSel", { fg = palette.black, bg = palette.primary })
	hl("PmenuSbar", { bg = palette.blue5 })
	hl("PmenuThumb", { bg = palette.blue3 })
	hl("PmenuMatch", { fg = palette.yellow2 })
	hl("PmenuMatchSel", { fg = palette.yellow1, bg = palette.primary })
	hl("WildMenu", { link = "Pmenu" })
	hl("SpellBad", { undercurl = true, sp = palette.vibrant_red })
	hl("SpellCap", { undercurl = true, sp = palette.yellow3 })
	hl("SpellLocal", { undercurl = true, sp = palette.cyan })
	hl("SpellRare", { undercurl = true, sp = palette.magenta })

	-- Syntax
	hl("Comment", { fg = palette.blue3, italic = true })
	hl("Constant", { fg = palette.green3 })
	hl("String", { fg = palette.green2 })
	hl("Character", { fg = palette.green2 })
	hl("Number", { fg = palette.green3 })
	hl("Boolean", { fg = palette.green3 })
	hl("Float", { fg = palette.green3 })
	hl("Identifier", { fg = palette.lightest })
	hl("Function", { fg = palette.bright_blue })
	hl("Statement", { fg = palette.magenta })
	hl("Conditional", { fg = palette.magenta })
	hl("Repeat", { fg = palette.magenta })
	hl("Label", { fg = palette.magenta })
	hl("Operator", { fg = palette.cyan })
	hl("Keyword", { fg = palette.magenta })
	hl("Exception", { fg = palette.vibrant_red })
	hl("PreProc", { fg = palette.cyan })
	hl("Include", { fg = palette.cyan })
	hl("Define", { fg = palette.cyan })
	hl("Macro", { fg = palette.cyan })
	hl("PreCondit", { fg = palette.cyan })
	hl("Type", { fg = palette.bright_blue })
	hl("StorageClass", { fg = palette.magenta })
	hl("Structure", { fg = palette.bright_blue })
	hl("Typedef", { fg = palette.bright_blue })
	hl("Special", { fg = palette.light })
	hl("SpecialChar", { fg = palette.light })
	hl("Tag", { fg = palette.red2 })
	hl("Delimiter", { fg = palette.cyan })
	hl("SpecialComment", { fg = palette.blue4, italic = true })
	hl("Debug", { fg = palette.red3 })
	hl("Underlined", { underline = true })
	hl("Error", { fg = palette.red1, bg = palette.red6 })
	hl("Todo", { fg = palette.yellow1, bg = palette.yellow6, bold = true })

	-- Diagnostics
	hl("DiagnosticError", { fg = palette.vibrant_red })
	hl("DiagnosticWarn", { fg = palette.yellow3 })
	hl("DiagnosticInfo", { fg = palette.blue4 })
	hl("DiagnosticHint", { fg = palette.green3 })
	hl("DiagnosticUnnecessary", { fg = palette.blue3 })
	hl("DiagnosticUnderlineError", { undercurl = true, sp = palette.vibrant_red })
	hl("DiagnosticUnderlineWarn", { undercurl = true, sp = palette.yellow3 })
	hl("DiagnosticUnderlineInfo", { undercurl = true, sp = palette.blue4 })
	hl("DiagnosticUnderlineHint", { undercurl = true, sp = palette.green3 })
	hl("DiagnosticVirtualTextError", { fg = palette.vibrant_red })
	hl("DiagnosticVirtualTextWarn", { fg = palette.yellow3 })
	hl("DiagnosticVirtualTextInfo", { fg = palette.blue4 })
	hl("DiagnosticVirtualTextHint", { fg = palette.green3 })
	
	-- LSP
	hl("LspReferenceText", { bg = palette.yellow6 })
	hl("LspReferenceRead", { bg = palette.yellow6 })
	hl("LspReferenceWrite", { bg = palette.yellow6, underline = true })
	hl("LspSignatureActiveParameter", { fg = palette.primary, bold = true })
	hl("LspCodeLens", { fg = palette.blue3 })
	hl("LspInlayHint", { fg = palette.blue3, italic = true })
	hl("LspInfoBorder", { link = "FloatBorder" })
	
	-- LSP Semantic Tokens
	hl("@lsp.type.boolean", { link = "@boolean" })
	hl("@lsp.type.builtinType", { link = "@type.builtin" })
	hl("@lsp.type.comment", { link = "@comment" })
	hl("@lsp.type.decorator", { link = "@attribute" })
	hl("@lsp.type.enum", { link = "@type" })
	hl("@lsp.type.enumMember", { link = "@constant" })
	hl("@lsp.type.escapeSequence", { link = "@string.escape" })
	hl("@lsp.type.formatSpecifier", { link = "@punctuation.special" })
	hl("@lsp.type.generic", { link = "@variable" })
	hl("@lsp.type.interface", { fg = palette.yellow2 })
	hl("@lsp.type.keyword", { link = "@keyword" })
	hl("@lsp.type.namespace", { link = "@module" })
	hl("@lsp.type.number", { link = "@number" })
	hl("@lsp.type.operator", { link = "@operator" })
	hl("@lsp.type.parameter", { link = "@variable.parameter" })
	hl("@lsp.type.property", { link = "@property" })
	hl("@lsp.type.selfKeyword", { link = "@variable.builtin" })
	hl("@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
	hl("@lsp.type.string", { link = "@string" })
	hl("@lsp.type.typeAlias", { link = "@type.definition" })
	hl("@lsp.type.unresolvedReference", { undercurl = true, sp = palette.vibrant_red })
	hl("@lsp.type.variable", { link = "@variable" })
	hl("@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
	hl("@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
	hl("@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
	hl("@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
	hl("@lsp.typemod.keyword.async", { link = "@keyword" })
	hl("@lsp.typemod.keyword.injected", { link = "@keyword" })
	hl("@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
	hl("@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
	hl("@lsp.typemod.operator.injected", { link = "@operator" })
	hl("@lsp.typemod.string.injected", { link = "@string" })
	hl("@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
	hl("@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
	hl("@lsp.typemod.typeAlias.defaultLibrary", { link = "@type.builtin" })
	hl("@lsp.typemod.variable.callable", { link = "@function" })
	hl("@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
	hl("@lsp.typemod.variable.injected", { link = "@variable" })
	hl("@lsp.typemod.variable.static", { link = "@constant" })

	-- TreeSitter
	hl("@variable", { fg = palette.lightest })
	hl("@variable.builtin", { fg = palette.red3 })
	hl("@variable.parameter", { fg = palette.red2 })
	hl("@variable.parameter.builtin", { fg = palette.red3 })
	hl("@variable.member", { fg = palette.bright_cyan })
	hl("@constant", { fg = palette.green3 })
	hl("@constant.builtin", { fg = palette.green3 })
	hl("@constant.macro", { fg = palette.cyan })
	hl("@module", { fg = palette.cyan })
	hl("@module.builtin", { fg = palette.red3 })
	hl("@label", { fg = palette.magenta })
	hl("@string", { fg = palette.green2 })
	hl("@string.documentation", { fg = palette.green3, italic = true })
	hl("@string.escape", { fg = palette.green3 })
	hl("@string.regexp", { fg = palette.green3 })
	hl("@character", { fg = palette.green2 })
	hl("@character.special", { fg = palette.green3 })
	hl("@number", { fg = palette.green3 })
	hl("@number.float", { fg = palette.green3 })
	hl("@boolean", { fg = palette.green3 })
	hl("@function", { fg = palette.bright_blue })
	hl("@function.builtin", { fg = palette.blue4 })
	hl("@function.call", { fg = palette.bright_blue })
	hl("@function.macro", { fg = palette.cyan })
	hl("@function.method", { fg = palette.bright_blue })
	hl("@function.method.call", { fg = palette.bright_blue })
	hl("@constructor", { fg = palette.yellow3 })
	hl("@keyword", { fg = palette.magenta })
	hl("@keyword.conditional", { fg = palette.magenta })
	hl("@keyword.repeat", { fg = palette.magenta })
	hl("@keyword.return", { fg = palette.magenta })
	hl("@keyword.exception", { fg = palette.vibrant_red })
	hl("@keyword.function", { fg = palette.magenta })
	hl("@keyword.operator", { fg = palette.magenta })
	hl("@keyword.import", { fg = palette.cyan })
	hl("@keyword.storage", { fg = palette.magenta })
	hl("@keyword.directive", { fg = palette.cyan })
	hl("@keyword.directive.define", { fg = palette.cyan })
	hl("@operator", { fg = palette.cyan })
	hl("@type", { fg = palette.bright_blue })
	hl("@type.builtin", { fg = palette.blue4 })
	hl("@type.definition", { fg = palette.bright_blue })
	hl("@type.qualifier", { fg = palette.magenta })
	hl("@attribute", { fg = palette.cyan })
	hl("@property", { fg = palette.bright_cyan })
	hl("@tag", { fg = palette.red2 })
	hl("@tag.attribute", { fg = palette.green2 })
	hl("@tag.delimiter", { fg = palette.cyan })
	hl("@tag.builtin", { fg = palette.red3 })
	hl("@punctuation.delimiter", { fg = palette.cyan })
	hl("@punctuation.bracket", { fg = palette.blue2 })
	hl("@punctuation.special", { fg = palette.bright_cyan })
	hl("@comment", { link = "Comment" })
	hl("@comment.documentation", { fg = palette.blue4, italic = true })
	hl("@comment.error", { fg = palette.vibrant_red })
	hl("@comment.warning", { fg = palette.yellow3 })
	hl("@comment.todo", { fg = palette.yellow1, bg = palette.yellow6, bold = true })
	hl("@comment.note", { fg = palette.blue4 })
	hl("@markup", { fg = palette.lightest })
	hl("@markup.strong", { bold = true })
	hl("@markup.emphasis", { italic = true })
	hl("@markup.italic", { italic = true })
	hl("@markup.strikethrough", { strikethrough = true })
	hl("@markup.underline", { underline = true })
	hl("@markup.heading", { fg = palette.primary, bold = true })
	hl("@markup.heading.1", { fg = palette.primary, bold = true })
	hl("@markup.heading.2", { fg = palette.magenta, bold = true })
	hl("@markup.heading.3", { fg = palette.bright_blue, bold = true })
	hl("@markup.heading.4", { fg = palette.cyan, bold = true })
	hl("@markup.heading.5", { fg = palette.yellow3 })
	hl("@markup.heading.6", { fg = palette.green3 })
	hl("@markup.link", { fg = palette.cyan, underline = true })
	hl("@markup.link.label", { fg = palette.blue4 })
	hl("@markup.link.url", { fg = palette.cyan, underline = true })
	hl("@markup.raw", { fg = palette.green2 })
	hl("@markup.raw.markdown_inline", { fg = palette.green3 })
	hl("@markup.list", { fg = palette.magenta })
	hl("@markup.list.checked", { fg = palette.green3 })
	hl("@markup.list.unchecked", { fg = palette.blue3 })
	hl("@diff.plus", { link = "DiffAdd" })
	hl("@diff.minus", { link = "DiffDelete" })
	hl("@diff.delta", { link = "DiffChange" })

	-- Git
	hl("GitSignsAdd", { fg = palette.green3 })
	hl("GitSignsChange", { fg = palette.yellow3 })
	hl("GitSignsDelete", { fg = palette.vibrant_red })
	hl("DiffAdd", { fg = palette.green2, bg = palette.green6 })
	hl("DiffChange", { fg = palette.yellow2, bg = palette.yellow6 })
	hl("DiffDelete", { fg = palette.red2, bg = palette.red6 })
	hl("DiffText", { fg = palette.yellow1, bg = palette.yellow5 })

	-- LSP & Completion Kinds
	hl("LspKindArray", { fg = palette.bright_blue })
	hl("LspKindBoolean", { fg = palette.green3 })
	hl("LspKindClass", { fg = palette.bright_blue })
	hl("LspKindColor", { fg = palette.primary })
	hl("LspKindConstant", { fg = palette.green3 })
	hl("LspKindConstructor", { fg = palette.yellow3 })
	hl("LspKindEnum", { fg = palette.bright_blue })
	hl("LspKindEnumMember", { fg = palette.green3 })
	hl("LspKindEvent", { fg = palette.primary })
	hl("LspKindField", { fg = palette.bright_cyan })
	hl("LspKindFile", { fg = palette.blue4 })
	hl("LspKindFolder", { fg = palette.blue4 })
	hl("LspKindFunction", { fg = palette.bright_blue })
	hl("LspKindInterface", { fg = palette.bright_blue })
	hl("LspKindKey", { fg = palette.bright_cyan })
	hl("LspKindKeyword", { fg = palette.magenta })
	hl("LspKindMethod", { fg = palette.bright_blue })
	hl("LspKindModule", { fg = palette.cyan })
	hl("LspKindNamespace", { fg = palette.cyan })
	hl("LspKindNull", { fg = palette.blue3 })
	hl("LspKindNumber", { fg = palette.green3 })
	hl("LspKindObject", { fg = palette.bright_blue })
	hl("LspKindOperator", { fg = palette.cyan })
	hl("LspKindPackage", { fg = palette.blue4 })
	hl("LspKindProperty", { fg = palette.bright_cyan })
	hl("LspKindReference", { fg = palette.cyan })
	hl("LspKindSnippet", { fg = palette.green2 })
	hl("LspKindString", { fg = palette.green2 })
	hl("LspKindStruct", { fg = palette.bright_blue })
	hl("LspKindText", { fg = palette.lightest })
	hl("LspKindTypeParameter", { fg = palette.bright_blue })
	hl("LspKindUnit", { fg = palette.green3 })
	hl("LspKindValue", { fg = palette.green3 })
	hl("LspKindVariable", { fg = palette.lightest })

	-- Snacks Picker
	hl("SnacksPicker", { fg = palette.light, bg = palette.black })
	hl("SnacksPickerBorder", { fg = palette.primary, bg = palette.black })
	hl("SnacksPickerTitle", { fg = palette.primary, bg = palette.black, bold = true })
	hl("SnacksPickerHeader", { fg = palette.primary, bold = true })
	hl("SnacksPickerItem", { fg = palette.light })
	hl("SnacksPickerItemPrefix", { fg = palette.yellow4 })
	hl("SnacksPickerItemTitle", { fg = palette.lightest })
	hl("SnacksPickerItemDescription", { fg = palette.green3, italic = true })
	hl("SnacksPickerItemDetail", { fg = palette.yellow3 })
	hl("SnacksPickerSelectedItem", { fg = palette.lightest, bg = palette.yellow6 })
	hl("SnacksPickerSelectedText", { fg = palette.yellow2 })
	hl("SnacksPickerInfo", { fg = palette.cyan })
	hl("SnacksPickerCurrentLine", { bg = palette.yellow6 })
	hl("SnacksPickerSpinner", { fg = palette.primary })
	hl("SnacksPickerSeparator", { fg = palette.yellow5 })
	hl("SnacksPickerFooter", { fg = palette.green3, italic = true })
	hl("SnacksPickerDir", { fg = palette.blue3 })
	hl("SnacksPickerFile", { fg = palette.lightest })
	hl("SnacksPickerDirectory", { fg = palette.blue4 })
	hl("SnacksPickerIcon", { fg = palette.blue4 })
	hl("SnacksPickerIconDirectory", { fg = palette.blue4 })
	hl("SnacksPickerIconFile", { fg = palette.blue3 })
	hl("SnacksPickerMatch", { fg = palette.yellow2, bold = true })
	hl("SnacksPickerList", { fg = palette.light, bg = palette.black })
	hl("SnacksPickerListNormal", { fg = palette.light, bg = palette.black })
end

return M
